package models

// AllModels enumerates every persisted model in the package. The test in
// enums_test.go walks this list to enforce the "GORM acronym fields need
// explicit gorm:\"column:...\" tag" convention documented in CLAUDE.md
// ("Phase 6+ load-bearing patterns").
//
// The list mirrors the registration in internal/db/postgres.go::AllModels()
// — they MUST stay in sync. Adding a new model means appending here too;
// the test in enums_test.go will catch any field on a new model that
// violates the acronym-tag rule.
//
// Order matches internal/db/postgres.go::AllModels() so the two lists are
// diffable at review time.
func AllModels() []interface{} {
	return []interface{}{
		&User{},
		&Account{},
		&Course{},
		&CourseSection{},
		&Enrollment{},
		&ContextModule{},
		&ContentTag{},
		&WikiPage{},
		&Assignment{},
		&Quiz{},
		&AssignmentGroup{},
		&Submission{},
		&SubmissionComment{},
		&GradingStandard{},
		&DeveloperKey{},
		&AccessToken{},
		&LTIToolConfiguration{},
		&ContextExternalTool{},
		&LTIResourceLink{},
		&LTILineItem{},
		&LTIResult{},
		&Nonce{},
		&DiscussionTopic{},
		&DiscussionEntry{},
		&DiscussionEntryRating{},
		&Folder{},
		&Attachment{},
		&SISBatch{},
		&SISBatchError{},
		&QuizQuestion{},
		&QuizSubmission{},
		&QuizSubmissionAnswer{},
		&Rubric{},
		&RubricAssociation{},
		&RubricAssessment{},
		&GradingPeriodGroup{},
		&GradingPeriod{},
		&AssignmentOverride{},
		&AssignmentOverrideStudent{},
		&LatePolicy{},
		&CalendarEvent{},
		&Conversation{},
		&ConversationParticipant{},
		&ConversationMessage{},
		&NotificationPreference{},
		&Notification{},
		&ContentMigration{},
		&LearningOutcomeGroup{},
		&LearningOutcome{},
		&LearningOutcomeResult{},
		&OutcomeAlignment{},
		&GroupCategory{},
		&Group{},
		&GroupMembership{},
		&BlueprintTemplate{},
		&BlueprintSubscription{},
		&BlueprintMigration{},
		&CoursePace{},
		&CoursePaceModuleItem{},
		&Collaboration{},
		&Conference{},
		&ConferenceParticipant{},
		&PageView{},
		&AuthenticationProvider{},
		&DiscussionEntryParticipant{},
		&DiscussionTopicParticipant{},
		&DiscussionEntryVersion{},
		&Announcement{},
		&AnnouncementReadReceipt{},
		&EnrollmentTerm{},
		&CommunicationChannel{},
		&NotificationDelivery{},
		&AuditLog{},
		&GradeChangeLog{},
		&CustomRole{},
		&RoleOverride{},
		&OneRosterConnection{},
		&OneRosterSyncLog{},
		&DocumentAnnotation{},
		&ParentalConsent{},
		&DataProcessingAgreement{},
		&AgeVerification{},
		&DataRetentionPolicy{},
		&DataDeletionRequest{},
		&DataExportRequest{},
		&PIIAccessLog{},
		&StudentAccommodation{},
		&AccommodationApplication{},
		&AttendanceRecord{},
		&Portfolio{},
		&PortfolioSection{},
		&PortfolioArtifact{},
		&PortfolioReflection{},
		&PortfolioTemplate{},
		&PortfolioComment{},
		&CourseHomeButton{},
		&TodaysLessonOverride{},
		&CourseVisit{},
		&PeerReview{},
		&QuestionBank{},
		&QuestionBankEntry{},
		&ModulePrerequisite{},
		&QuizQuestionGroup{},
		&FeatureFlag{},
		&CustomGradebookColumn{},
		&CustomColumnDatum{},
		&ConditionalReleaseRule{},
		&ConditionalReleaseScoringRange{},
		&ConditionalReleaseAssignmentSet{},
		&ConditionalReleaseAssignmentSetAssociation{},
		&ConditionalReleaseAssignmentSetAction{},
		&AppointmentGroup{},
		&AppointmentSlot{},
		&AppointmentReservation{},
		&OutcomeProficiency{},
		&OutcomeProficiencyRating{},
		&PairingCode{},
		&DiscussionCheckpoint{},
		&DiscussionCheckpointSubmission{},
		&ContentEmbedding{},
		&SharedContent{},
		&SharedContentFavorite{},
		&QuizItemBank{},
		&QuizItemBankItem{},
		&QuizStimulus{},
		&QuizQuestionOutcomeAlignment{},
		&GamificationEvent{},
		&GamificationRule{},
		&GamificationRuleEvaluation{},
		&GamificationCurrencyType{},
		&GamificationWalletBalance{},
		&GamificationWalletTransaction{},
		&GamificationFerpaFieldTag{},
		&ContentView{},
		&GamificationBadge{},
		&GamificationBadgeAward{},
		&GamificationLeaderboardSnapshot{},
		&Setting{},
		// Phase 9-10 auth models not in AutoMigrate (migration-only).
		&FederatedIdentity{},
		&UserRecoveryCode{},
		&UserWebauthnCredential{},
		// Planner / mastery — not in AutoMigrate but persisted.
		&PlannerNote{},
		&PlannerOverride{},
	}
}
