-- 000016_backfill_missing_tables.down.sql
--
-- Reverses 000016_backfill_missing_tables.up.sql. With IF EXISTS guards
-- on every statement this is safe to run against a partially-applied DB.
--
-- Order:
--   1. Drop the 174 indexes added by the up migration (some auto-cascade
--      with their host tables or columns later, but explicit DROPs make
--      the intent visible in code review).
--   2. ALTER TABLE ... DROP COLUMN for the 270 columns added by the up
--      migration. NOTE: this is data-destructive on any column that
--      held production data — run only against fresh / scratch DBs.
--   3. DROP TABLE for the 5 tables added by the up migration.

-- === 1. Indexes ===
DROP INDEX IF EXISTS idx_access_tokens_developer_key_id;
DROP INDEX IF EXISTS idx_access_tokens_refresh_token;
DROP INDEX IF EXISTS idx_access_tokens_token;
DROP INDEX IF EXISTS idx_access_tokens_user_id;
DROP INDEX IF EXISTS idx_accommodation_applications_accommodation_id;
DROP INDEX IF EXISTS idx_accommodation_applications_resource_id;
DROP INDEX IF EXISTS idx_accommodation_applications_user_id;
DROP INDEX IF EXISTS idx_age_verifications_user_id;
DROP INDEX IF EXISTS idx_annotation_submission_page;
DROP INDEX IF EXISTS idx_announcement_user;
DROP INDEX IF EXISTS idx_announcements_account_id;
DROP INDEX IF EXISTS idx_announcements_course_id;
DROP INDEX IF EXISTS idx_appointment_reservations_group_id;
DROP INDEX IF EXISTS idx_appointment_slots_start_at;
DROP INDEX IF EXISTS idx_assignment_override_students_assignment_id;
DROP INDEX IF EXISTS idx_assignment_override_students_assignment_override_id;
DROP INDEX IF EXISTS idx_assignment_overrides_assignment_id;
DROP INDEX IF EXISTS idx_assignments_group_category_id;
DROP INDEX IF EXISTS idx_attendance_records_course_id;
DROP INDEX IF EXISTS idx_attendance_records_date;
DROP INDEX IF EXISTS idx_attendance_records_section_id;
DROP INDEX IF EXISTS idx_attendance_records_user_id;
DROP INDEX IF EXISTS idx_audit_logs_account_id;
DROP INDEX IF EXISTS idx_audit_logs_created_at;
DROP INDEX IF EXISTS idx_audit_logs_event_type;
DROP INDEX IF EXISTS idx_authentication_providers_account_id;
DROP INDEX IF EXISTS idx_blueprint_migrations_blueprint_template_id;
DROP INDEX IF EXISTS idx_blueprint_templates_course_id;
DROP INDEX IF EXISTS idx_cal_event_context;
DROP INDEX IF EXISTS idx_calendar_events_start_at;
DROP INDEX IF EXISTS idx_collab_context;
DROP INDEX IF EXISTS idx_communication_channels_user_id;
DROP INDEX IF EXISTS idx_conditional_release_assignment_set_actions_set_id;
DROP INDEX IF EXISTS idx_conditional_release_assignment_set_actions_student_id;
DROP INDEX IF EXISTS idx_conditional_release_assignment_set_associations_ass26affdd9;
DROP INDEX IF EXISTS idx_conditional_release_assignment_set_associations_set_id;
DROP INDEX IF EXISTS idx_conditional_release_assignment_sets_scoring_range_id;
DROP INDEX IF EXISTS idx_conditional_release_rules_course_id;
DROP INDEX IF EXISTS idx_conditional_release_rules_workflow_state;
DROP INDEX IF EXISTS idx_conditional_release_scoring_ranges_rule_id;
DROP INDEX IF EXISTS idx_conf_context;
DROP INDEX IF EXISTS idx_conf_user;
DROP INDEX IF EXISTS idx_content_migrations_course_id;
DROP INDEX IF EXISTS idx_content_tags_context_module_id;
DROP INDEX IF EXISTS idx_context_external_tools_context_id;
DROP INDEX IF EXISTS idx_context_external_tools_developer_key_id;
DROP INDEX IF EXISTS idx_context_modules_course_id;
DROP INDEX IF EXISTS idx_conv_user;
DROP INDEX IF EXISTS idx_conversation_messages_conversation_id;
DROP INDEX IF EXISTS idx_conversations_last_message_at;
DROP INDEX IF EXISTS idx_course_date;
DROP INDEX IF EXISTS idx_course_paces_course_id;
DROP INDEX IF EXISTS idx_course_paces_course_section_id;
DROP INDEX IF EXISTS idx_course_paces_user_id;
DROP INDEX IF EXISTS idx_course_sections_course_id;
DROP INDEX IF EXISTS idx_course_sections_sis_section_id;
DROP INDEX IF EXISTS idx_courses_sis_course_id;
DROP INDEX IF EXISTS idx_custom_gradebook_column_data_user_id;
DROP INDEX IF EXISTS idx_custom_roles_account_id;
DROP INDEX IF EXISTS idx_custom_roles_base_role_type;
DROP INDEX IF EXISTS idx_custom_roles_created_by_user_id;
DROP INDEX IF EXISTS idx_data_deletion_requests_requested_by_id;
DROP INDEX IF EXISTS idx_data_deletion_requests_user_id;
DROP INDEX IF EXISTS idx_data_export_requests_requested_by_id;
DROP INDEX IF EXISTS idx_data_export_requests_user_id;
DROP INDEX IF EXISTS idx_data_processing_agreements_account_id;
DROP INDEX IF EXISTS idx_data_retention_policies_account_id;
DROP INDEX IF EXISTS idx_developer_keys_client_id;
DROP INDEX IF EXISTS idx_discussion_checkpoint_submissions_discussion_checkpoint_id;
DROP INDEX IF EXISTS idx_discussion_checkpoints_discussion_topic_id;
DROP INDEX IF EXISTS idx_discussion_entries_discussion_topic_id;
DROP INDEX IF EXISTS idx_discussion_entries_parent_id;
DROP INDEX IF EXISTS idx_discussion_entry_versions_discussion_entry_id;
DROP INDEX IF EXISTS idx_document_annotations_parent_annotation_id;
DROP INDEX IF EXISTS idx_document_annotations_submission_id;
DROP INDEX IF EXISTS idx_document_annotations_user_id;
DROP INDEX IF EXISTS idx_enrollment_terms_account_id;
DROP INDEX IF EXISTS idx_enrollment_terms_sis_term_id;
DROP INDEX IF EXISTS idx_enrollments_associated_user_id;
DROP INDEX IF EXISTS idx_enrollments_course_section_id;
DROP INDEX IF EXISTS idx_entry_user;
DROP INDEX IF EXISTS idx_feature_flags_context_id;
DROP INDEX IF EXISTS idx_feature_flags_context_type;
DROP INDEX IF EXISTS idx_folders_parent_folder_id;
DROP INDEX IF EXISTS idx_grade_change_logs_assignment_id;
DROP INDEX IF EXISTS idx_grade_change_logs_created_at;
DROP INDEX IF EXISTS idx_grade_change_logs_grader_id;
DROP INDEX IF EXISTS idx_grading_period_groups_account_id;
DROP INDEX IF EXISTS idx_grading_periods_grading_period_group_id;
DROP INDEX IF EXISTS idx_group_categories_account_id;
DROP INDEX IF EXISTS idx_group_categories_course_id;
DROP INDEX IF EXISTS idx_group_user;
DROP INDEX IF EXISTS idx_groups_context_id;
DROP INDEX IF EXISTS idx_groups_group_category_id;
DROP INDEX IF EXISTS idx_late_policies_course_id;
DROP INDEX IF EXISTS idx_learning_outcome_groups_context_id;
DROP INDEX IF EXISTS idx_learning_outcome_groups_parent_group_id;
DROP INDEX IF EXISTS idx_learning_outcome_results_learning_outcome_id;
DROP INDEX IF EXISTS idx_learning_outcome_results_user_id;
DROP INDEX IF EXISTS idx_learning_outcomes_context_id;
DROP INDEX IF EXISTS idx_learning_outcomes_outcome_group_id;
DROP INDEX IF EXISTS idx_lti_line_items_assignment_id;
DROP INDEX IF EXISTS idx_lti_line_items_course_id;
DROP INDEX IF EXISTS idx_lti_line_items_resource_link_id;
DROP INDEX IF EXISTS idx_lti_resource_links_context_external_tool_id;
DROP INDEX IF EXISTS idx_lti_resource_links_lookup_uuid;
DROP INDEX IF EXISTS idx_lti_resource_links_resource_link_id;
DROP INDEX IF EXISTS idx_lti_results_line_item_id;
DROP INDEX IF EXISTS idx_lti_results_user_id;
DROP INDEX IF EXISTS idx_lti_tool_configurations_developer_key_id;
DROP INDEX IF EXISTS idx_module_prerequisites_module_id;
DROP INDEX IF EXISTS idx_nonces_expires_at;
DROP INDEX IF EXISTS idx_nonces_value;
DROP INDEX IF EXISTS idx_notification_deliveries_delivery_status;
DROP INDEX IF EXISTS idx_notification_deliveries_notification_id;
DROP INDEX IF EXISTS idx_notification_deliveries_scheduled_for;
DROP INDEX IF EXISTS idx_notifications_is_read;
DROP INDEX IF EXISTS idx_one_roster_connections_account_id;
DROP INDEX IF EXISTS idx_one_roster_sync_logs_connection_id;
DROP INDEX IF EXISTS idx_outcome_alignments_assignment_id;
DROP INDEX IF EXISTS idx_outcome_alignments_course_id;
DROP INDEX IF EXISTS idx_outcome_assignment;
DROP INDEX IF EXISTS idx_outcome_proficiency_ratings_outcome_proficiency_id;
DROP INDEX IF EXISTS idx_override_user;
DROP INDEX IF EXISTS idx_pace_module_item;
DROP INDEX IF EXISTS idx_page_views_context_id;
DROP INDEX IF EXISTS idx_parental_consents_parent_user_id;
DROP INDEX IF EXISTS idx_parental_consents_student_id;
DROP INDEX IF EXISTS idx_parental_consents_verification_token;
DROP INDEX IF EXISTS idx_peer_reviews_assignment_id;
DROP INDEX IF EXISTS idx_peer_reviews_reviewee_id;
DROP INDEX IF EXISTS idx_peer_reviews_reviewer_id;
DROP INDEX IF EXISTS idx_peer_reviews_submission_id;
DROP INDEX IF EXISTS idx_pii_access_logs_accessor_id;
DROP INDEX IF EXISTS idx_pii_access_logs_student_id;
DROP INDEX IF EXISTS idx_portfolio_artifacts_portfolio_id;
DROP INDEX IF EXISTS idx_portfolio_comments_artifact_id;
DROP INDEX IF EXISTS idx_portfolio_comments_portfolio_id;
DROP INDEX IF EXISTS idx_portfolio_comments_section_id;
DROP INDEX IF EXISTS idx_portfolio_reflections_artifact_id;
DROP INDEX IF EXISTS idx_portfolio_templates_account_id;
DROP INDEX IF EXISTS idx_portfolios_public_url;
DROP INDEX IF EXISTS idx_portfolios_slug;
DROP INDEX IF EXISTS idx_qq_outcome;
DROP INDEX IF EXISTS idx_question_bank_entries_question_bank_id;
DROP INDEX IF EXISTS idx_question_banks_course_id;
DROP INDEX IF EXISTS idx_quiz_item_banks_created_by_user_id;
DROP INDEX IF EXISTS idx_quiz_question_groups_quiz_id;
DROP INDEX IF EXISTS idx_quiz_question_outcome_alignments_outcome_id;
DROP INDEX IF EXISTS idx_quiz_question_outcome_alignments_quiz_question_id;
DROP INDEX IF EXISTS idx_quiz_questions_quiz_question_group_id;
DROP INDEX IF EXISTS idx_quiz_submission_answers_quiz_submission_id;
DROP INDEX IF EXISTS idx_rating_entry_user;
DROP INDEX IF EXISTS idx_role_overrides_account_id;
DROP INDEX IF EXISTS idx_role_overrides_role_id;
DROP INDEX IF EXISTS idx_rubric_assessments_rubric_id;
DROP INDEX IF EXISTS idx_rubric_associations_rubric_id;
DROP INDEX IF EXISTS idx_shared_content_account_id;
DROP INDEX IF EXISTS idx_shared_content_author_user_id;
DROP INDEX IF EXISTS idx_shared_content_favorites_user_id;
DROP INDEX IF EXISTS idx_shared_content_grade_level;
DROP INDEX IF EXISTS idx_shared_content_resource_type;
DROP INDEX IF EXISTS idx_shared_content_source_content_id;
DROP INDEX IF EXISTS idx_shared_content_source_course_id;
DROP INDEX IF EXISTS idx_shared_content_subject;
DROP INDEX IF EXISTS idx_sis_batch_errors_sis_batch_id;
DROP INDEX IF EXISTS idx_sis_batches_account_id;
DROP INDEX IF EXISTS idx_student_accommodations_course_id;
DROP INDEX IF EXISTS idx_student_accommodations_user_id;
DROP INDEX IF EXISTS idx_submission_assignment_user;
DROP INDEX IF EXISTS idx_template_child;
DROP INDEX IF EXISTS idx_topic_user;
DROP INDEX IF EXISTS idx_user_course;
DROP INDEX IF EXISTS idx_wiki_pages_url;

-- === 2. Columns ===
ALTER TABLE access_tokens DROP COLUMN IF EXISTS token_hint;
ALTER TABLE access_tokens DROP COLUMN IF EXISTS workflow_state;
ALTER TABLE accommodation_applications DROP COLUMN IF EXISTS accommodation_id;
ALTER TABLE accommodation_applications DROP COLUMN IF EXISTS resource_type;
ALTER TABLE accommodation_applications DROP COLUMN IF EXISTS resource_id;
ALTER TABLE accommodation_applications DROP COLUMN IF EXISTS user_id;
ALTER TABLE accommodation_applications DROP COLUMN IF EXISTS adjusted_due_at;
ALTER TABLE accommodation_applications DROP COLUMN IF EXISTS adjusted_time_limit;
ALTER TABLE accounts DROP COLUMN IF EXISTS max_upload_size_mb;
ALTER TABLE age_verifications DROP COLUMN IF EXISTS is_under13;
ALTER TABLE age_verifications DROP COLUMN IF EXISTS is_minor;
ALTER TABLE age_verifications DROP COLUMN IF EXISTS verified_by;
ALTER TABLE age_verifications DROP COLUMN IF EXISTS requires_consent;
ALTER TABLE announcements DROP COLUMN IF EXISTS course_id;
ALTER TABLE announcements DROP COLUMN IF EXISTS account_id;
ALTER TABLE announcements DROP COLUMN IF EXISTS priority;
ALTER TABLE announcements DROP COLUMN IF EXISTS require_ack;
ALTER TABLE announcements DROP COLUMN IF EXISTS target_audience;
ALTER TABLE announcements DROP COLUMN IF EXISTS allow_comments;
ALTER TABLE announcements DROP COLUMN IF EXISTS is_global;
ALTER TABLE assignment_groups DROP COLUMN IF EXISTS rules;
ALTER TABLE assignment_override_students DROP COLUMN IF EXISTS assignment_id;
ALTER TABLE assignment_overrides DROP COLUMN IF EXISTS course_section_id;
ALTER TABLE assignment_overrides DROP COLUMN IF EXISTS workflow_state;
ALTER TABLE assignments DROP COLUMN IF EXISTS anonymous_grading;
ALTER TABLE assignments DROP COLUMN IF EXISTS post_policy;
ALTER TABLE assignments DROP COLUMN IF EXISTS peer_reviews_enabled;
ALTER TABLE assignments DROP COLUMN IF EXISTS peer_review_count;
ALTER TABLE assignments DROP COLUMN IF EXISTS group_category_id;
ALTER TABLE attachments DROP COLUMN IF EXISTS md5;
ALTER TABLE attachments DROP COLUMN IF EXISTS storage_path;
ALTER TABLE attachments DROP COLUMN IF EXISTS file_state;
ALTER TABLE attachments DROP COLUMN IF EXISTS upload_status;
ALTER TABLE attendance_records DROP COLUMN IF EXISTS section_id;
ALTER TABLE attendance_records DROP COLUMN IF EXISTS marked_by_id;
ALTER TABLE audit_logs DROP COLUMN IF EXISTS account_id;
ALTER TABLE audit_logs DROP COLUMN IF EXISTS action;
ALTER TABLE audit_logs DROP COLUMN IF EXISTS payload;
ALTER TABLE audit_logs DROP COLUMN IF EXISTS user_agent;
ALTER TABLE authentication_providers DROP COLUMN IF EXISTS id_p_entity_id;
ALTER TABLE authentication_providers DROP COLUMN IF EXISTS id_p_certificate;
ALTER TABLE authentication_providers DROP COLUMN IF EXISTS ldap_host;
ALTER TABLE authentication_providers DROP COLUMN IF EXISTS ldap_port;
ALTER TABLE authentication_providers DROP COLUMN IF EXISTS ldap_base;
ALTER TABLE authentication_providers DROP COLUMN IF EXISTS ldap_filter;
ALTER TABLE authentication_providers DROP COLUMN IF EXISTS ldap_bind_dn;
ALTER TABLE authentication_providers DROP COLUMN IF EXISTS ldap_bind_password;
ALTER TABLE authentication_providers DROP COLUMN IF EXISTS ldap_use_tls;
ALTER TABLE authentication_providers DROP COLUMN IF EXISTS ldap_login_attribute;
ALTER TABLE authentication_providers DROP COLUMN IF EXISTS cas_base_url;
ALTER TABLE authentication_providers DROP COLUMN IF EXISTS cas_login_url;
ALTER TABLE authentication_providers DROP COLUMN IF EXISTS cas_validate_url;
ALTER TABLE authentication_providers DROP COLUMN IF EXISTS cas_logout_url;
ALTER TABLE authentication_providers DROP COLUMN IF EXISTS federated_attributes;
ALTER TABLE blueprint_templates DROP COLUMN IF EXISTS use_default_restrictions;
ALTER TABLE calendar_events DROP COLUMN IF EXISTS created_by_user_id;
ALTER TABLE communication_channels DROP COLUMN IF EXISTS channel_type;
ALTER TABLE communication_channels DROP COLUMN IF EXISTS address;
ALTER TABLE communication_channels DROP COLUMN IF EXISTS confirmed;
ALTER TABLE communication_channels DROP COLUMN IF EXISTS confirm_code;
ALTER TABLE communication_channels DROP COLUMN IF EXISTS confirmed_at;
ALTER TABLE conferences DROP COLUMN IF EXISTS recordings;
ALTER TABLE conferences DROP COLUMN IF EXISTS settings;
ALTER TABLE content_migrations DROP COLUMN IF EXISTS attachment;
ALTER TABLE content_tags DROP COLUMN IF EXISTS new_tab;
ALTER TABLE context_external_tools DROP COLUMN IF EXISTS custom_fields;
ALTER TABLE conversation_messages DROP COLUMN IF EXISTS user_id;
ALTER TABLE conversation_messages DROP COLUMN IF EXISTS workflow_state;
ALTER TABLE conversation_participants DROP COLUMN IF EXISTS last_read_at;
ALTER TABLE conversations DROP COLUMN IF EXISTS created_by_user_id;
ALTER TABLE course_home_buttons DROP COLUMN IF EXISTS button_type;
ALTER TABLE course_home_buttons DROP COLUMN IF EXISTS link_id;
ALTER TABLE course_home_buttons DROP COLUMN IF EXISTS link_url;
ALTER TABLE course_visits DROP COLUMN IF EXISTS last_url;
ALTER TABLE course_visits DROP COLUMN IF EXISTS last_title;
ALTER TABLE courses DROP COLUMN IF EXISTS license;
ALTER TABLE courses DROP COLUMN IF EXISTS apply_group_weights;
ALTER TABLE courses DROP COLUMN IF EXISTS navigation_tabs;
ALTER TABLE custom_roles DROP COLUMN IF EXISTS permissions;
ALTER TABLE custom_roles DROP COLUMN IF EXISTS created_by_user_id;
ALTER TABLE data_deletion_requests DROP COLUMN IF EXISTS requested_by_id;
ALTER TABLE data_deletion_requests DROP COLUMN IF EXISTS request_type;
ALTER TABLE data_deletion_requests DROP COLUMN IF EXISTS data_scope;
ALTER TABLE data_deletion_requests DROP COLUMN IF EXISTS status;
ALTER TABLE data_deletion_requests DROP COLUMN IF EXISTS reviewed_by_id;
ALTER TABLE data_deletion_requests DROP COLUMN IF EXISTS reviewed_at;
ALTER TABLE data_deletion_requests DROP COLUMN IF EXISTS deletion_log;
ALTER TABLE data_export_requests DROP COLUMN IF EXISTS requested_by_id;
ALTER TABLE data_export_requests DROP COLUMN IF EXISTS data_scope;
ALTER TABLE data_export_requests DROP COLUMN IF EXISTS status;
ALTER TABLE data_export_requests DROP COLUMN IF EXISTS file_size_bytes;
ALTER TABLE data_processing_agreements DROP COLUMN IF EXISTS retention_period;
ALTER TABLE data_processing_agreements DROP COLUMN IF EXISTS status;
ALTER TABLE data_processing_agreements DROP COLUMN IF EXISTS expires_at;
ALTER TABLE data_retention_policies DROP COLUMN IF EXISTS data_category;
ALTER TABLE data_retention_policies DROP COLUMN IF EXISTS retention_period;
ALTER TABLE data_retention_policies DROP COLUMN IF EXISTS retention_action;
ALTER TABLE data_retention_policies DROP COLUMN IF EXISTS auto_apply;
ALTER TABLE data_retention_policies DROP COLUMN IF EXISTS description;
ALTER TABLE developer_keys DROP COLUMN IF EXISTS redirect_uris;
ALTER TABLE developer_keys DROP COLUMN IF EXISTS icon;
ALTER TABLE developer_keys DROP COLUMN IF EXISTS scopes;
ALTER TABLE developer_keys DROP COLUMN IF EXISTS require_scopes;
ALTER TABLE developer_keys DROP COLUMN IF EXISTS is_lti_key;
ALTER TABLE discussion_entry_participants DROP COLUMN IF EXISTS read_at;
ALTER TABLE discussion_topic_participants DROP COLUMN IF EXISTS forced_read_state;
ALTER TABLE discussion_topic_participants DROP COLUMN IF EXISTS last_read_at;
ALTER TABLE discussion_topics DROP COLUMN IF EXISTS posted_at;
ALTER TABLE discussion_topics DROP COLUMN IF EXISTS sort_by_rating;
ALTER TABLE discussion_topics DROP COLUMN IF EXISTS assignment_id;
ALTER TABLE document_annotations DROP COLUMN IF EXISTS page_number;
ALTER TABLE document_annotations DROP COLUMN IF EXISTS selection_start;
ALTER TABLE document_annotations DROP COLUMN IF EXISTS selection_end;
ALTER TABLE document_annotations DROP COLUMN IF EXISTS path_data;
ALTER TABLE document_annotations DROP COLUMN IF EXISTS parent_annotation_id;
ALTER TABLE document_annotations DROP COLUMN IF EXISTS resolved_by_user_id;
ALTER TABLE document_annotations DROP COLUMN IF EXISTS workflow_state;
ALTER TABLE enrollment_terms DROP COLUMN IF EXISTS account_id;
ALTER TABLE enrollments DROP COLUMN IF EXISTS type;
ALTER TABLE enrollments DROP COLUMN IF EXISTS last_activity_at;
ALTER TABLE enrollments DROP COLUMN IF EXISTS associated_user_id;
ALTER TABLE grade_change_logs DROP COLUMN IF EXISTS submission_id;
ALTER TABLE grade_change_logs DROP COLUMN IF EXISTS excused;
ALTER TABLE grade_change_logs DROP COLUMN IF EXISTS grading_method;
ALTER TABLE grading_period_groups DROP COLUMN IF EXISTS display_totals;
ALTER TABLE grading_periods DROP COLUMN IF EXISTS workflow_state;
ALTER TABLE group_categories DROP COLUMN IF EXISTS course_id;
ALTER TABLE group_categories DROP COLUMN IF EXISTS account_id;
ALTER TABLE group_categories DROP COLUMN IF EXISTS role;
ALTER TABLE learning_outcome_groups DROP COLUMN IF EXISTS parent_group_id;
ALTER TABLE learning_outcome_results DROP COLUMN IF EXISTS submitted_at;
ALTER TABLE learning_outcomes DROP COLUMN IF EXISTS outcome_group_id;
ALTER TABLE learning_outcomes DROP COLUMN IF EXISTS ratings_data;
ALTER TABLE lti_line_items DROP COLUMN IF EXISTS resource_link_id_str;
ALTER TABLE lti_line_items DROP COLUMN IF EXISTS lti_submission_type;
ALTER TABLE lti_resource_links DROP COLUMN IF EXISTS custom_parameters;
ALTER TABLE lti_resource_links DROP COLUMN IF EXISTS lookup_uuid;
ALTER TABLE lti_results DROP COLUMN IF EXISTS timestamp;
ALTER TABLE lti_tool_configurations DROP COLUMN IF EXISTS title;
ALTER TABLE lti_tool_configurations DROP COLUMN IF EXISTS o_id_c_initiation_url;
ALTER TABLE lti_tool_configurations DROP COLUMN IF EXISTS tool_id;
ALTER TABLE lti_tool_configurations DROP COLUMN IF EXISTS scopes;
ALTER TABLE nonces DROP COLUMN IF EXISTS value;
ALTER TABLE notification_deliveries DROP COLUMN IF EXISTS channel_type;
ALTER TABLE notification_deliveries DROP COLUMN IF EXISTS address;
ALTER TABLE notification_deliveries DROP COLUMN IF EXISTS subject;
ALTER TABLE notification_deliveries DROP COLUMN IF EXISTS body;
ALTER TABLE notification_deliveries DROP COLUMN IF EXISTS delivery_status;
ALTER TABLE notification_deliveries DROP COLUMN IF EXISTS digest_type;
ALTER TABLE notification_deliveries DROP COLUMN IF EXISTS max_retries;
ALTER TABLE notification_deliveries DROP COLUMN IF EXISTS last_error;
ALTER TABLE notification_deliveries DROP COLUMN IF EXISTS delivered_at;
ALTER TABLE notification_deliveries DROP COLUMN IF EXISTS scheduled_for;
ALTER TABLE notification_preferences DROP COLUMN IF EXISTS policy;
ALTER TABLE notification_preferences DROP COLUMN IF EXISTS notify_new_message;
ALTER TABLE notification_preferences DROP COLUMN IF EXISTS notify_event_start;
ALTER TABLE notification_preferences DROP COLUMN IF EXISTS notify_submission_grade;
ALTER TABLE notification_preferences DROP COLUMN IF EXISTS notify_new_announcement;
ALTER TABLE notifications DROP COLUMN IF EXISTS title;
ALTER TABLE notifications DROP COLUMN IF EXISTS related_user_id;
ALTER TABLE notifications DROP COLUMN IF EXISTS is_read;
ALTER TABLE one_roster_connections DROP COLUMN IF EXISTS scope;
ALTER TABLE one_roster_connections DROP COLUMN IF EXISTS last_sync_error;
ALTER TABLE one_roster_connections DROP COLUMN IF EXISTS sync_filter;
ALTER TABLE one_roster_connections DROP COLUMN IF EXISTS auto_sync;
ALTER TABLE one_roster_connections DROP COLUMN IF EXISTS auto_sync_interval;
ALTER TABLE one_roster_sync_logs DROP COLUMN IF EXISTS status;
ALTER TABLE one_roster_sync_logs DROP COLUMN IF EXISTS orgs_created;
ALTER TABLE one_roster_sync_logs DROP COLUMN IF EXISTS orgs_updated;
ALTER TABLE one_roster_sync_logs DROP COLUMN IF EXISTS users_created;
ALTER TABLE one_roster_sync_logs DROP COLUMN IF EXISTS users_updated;
ALTER TABLE one_roster_sync_logs DROP COLUMN IF EXISTS classes_created;
ALTER TABLE one_roster_sync_logs DROP COLUMN IF EXISTS classes_updated;
ALTER TABLE one_roster_sync_logs DROP COLUMN IF EXISTS enrollments_created;
ALTER TABLE one_roster_sync_logs DROP COLUMN IF EXISTS enrollments_updated;
ALTER TABLE one_roster_sync_logs DROP COLUMN IF EXISTS completed_at;
ALTER TABLE one_roster_sync_logs DROP COLUMN IF EXISTS error_details;
ALTER TABLE outcome_alignments DROP COLUMN IF EXISTS assignment_id;
ALTER TABLE outcome_alignments DROP COLUMN IF EXISTS course_id;
ALTER TABLE page_views DROP COLUMN IF EXISTS action;
ALTER TABLE parental_consents DROP COLUMN IF EXISTS parent_user_id;
ALTER TABLE parental_consents DROP COLUMN IF EXISTS parent_name;
ALTER TABLE parental_consents DROP COLUMN IF EXISTS status;
ALTER TABLE parental_consents DROP COLUMN IF EXISTS consent_method;
ALTER TABLE parental_consents DROP COLUMN IF EXISTS verification_token;
ALTER TABLE parental_consents DROP COLUMN IF EXISTS consented_at;
ALTER TABLE parental_consents DROP COLUMN IF EXISTS expires_at;
ALTER TABLE parental_consents DROP COLUMN IF EXISTS user_agent;
ALTER TABLE parental_consents DROP COLUMN IF EXISTS notes;
ALTER TABLE pii_access_logs DROP COLUMN IF EXISTS accessor_id;
ALTER TABLE pii_access_logs DROP COLUMN IF EXISTS student_id;
ALTER TABLE pii_access_logs DROP COLUMN IF EXISTS data_field;
ALTER TABLE pii_access_logs DROP COLUMN IF EXISTS resource;
ALTER TABLE pii_access_logs DROP COLUMN IF EXISTS resource_id;
ALTER TABLE pii_access_logs DROP COLUMN IF EXISTS user_agent;
ALTER TABLE pii_access_logs DROP COLUMN IF EXISTS justification;
ALTER TABLE portfolio_artifacts DROP COLUMN IF EXISTS portfolio_id;
ALTER TABLE portfolio_artifacts DROP COLUMN IF EXISTS section_id;
ALTER TABLE portfolio_artifacts DROP COLUMN IF EXISTS content_url;
ALTER TABLE portfolio_artifacts DROP COLUMN IF EXISTS thumbnail_url;
ALTER TABLE portfolio_artifacts DROP COLUMN IF EXISTS source_type;
ALTER TABLE portfolio_artifacts DROP COLUMN IF EXISTS source_course_id;
ALTER TABLE portfolio_artifacts DROP COLUMN IF EXISTS source_id;
ALTER TABLE portfolio_artifacts DROP COLUMN IF EXISTS file_type;
ALTER TABLE portfolio_artifacts DROP COLUMN IF EXISTS file_size_bytes;
ALTER TABLE portfolio_artifacts DROP COLUMN IF EXISTS tags;
ALTER TABLE portfolio_artifacts DROP COLUMN IF EXISTS outcome_ids;
ALTER TABLE portfolio_artifacts DROP COLUMN IF EXISTS is_featured;
ALTER TABLE portfolio_comments DROP COLUMN IF EXISTS section_id;
ALTER TABLE portfolio_comments DROP COLUMN IF EXISTS artifact_id;
ALTER TABLE portfolio_comments DROP COLUMN IF EXISTS content;
ALTER TABLE portfolio_reflections DROP COLUMN IF EXISTS artifact_id;
ALTER TABLE portfolio_reflections DROP COLUMN IF EXISTS prompt_text;
ALTER TABLE portfolio_sections DROP COLUMN IF EXISTS content;
ALTER TABLE portfolio_sections DROP COLUMN IF EXISTS is_visible;
ALTER TABLE portfolio_templates DROP COLUMN IF EXISTS created_by_id;
ALTER TABLE portfolio_templates DROP COLUMN IF EXISTS name;
ALTER TABLE portfolio_templates DROP COLUMN IF EXISTS theme_id;
ALTER TABLE portfolio_templates DROP COLUMN IF EXISTS sections;
ALTER TABLE portfolio_templates DROP COLUMN IF EXISTS is_public;
ALTER TABLE portfolio_templates DROP COLUMN IF EXISTS usage_count;
ALTER TABLE portfolios DROP COLUMN IF EXISTS slug;
ALTER TABLE portfolios DROP COLUMN IF EXISTS theme_id;
ALTER TABLE portfolios DROP COLUMN IF EXISTS custom_css;
ALTER TABLE portfolios DROP COLUMN IF EXISTS header_image_url;
ALTER TABLE portfolios DROP COLUMN IF EXISTS avatar_url;
ALTER TABLE portfolios DROP COLUMN IF EXISTS tagline;
ALTER TABLE portfolios DROP COLUMN IF EXISTS contact_email;
ALTER TABLE portfolios DROP COLUMN IF EXISTS linked_in_url;
ALTER TABLE portfolios DROP COLUMN IF EXISTS website_url;
ALTER TABLE portfolios DROP COLUMN IF EXISTS is_public;
ALTER TABLE portfolios DROP COLUMN IF EXISTS public_url;
ALTER TABLE portfolios DROP COLUMN IF EXISTS custom_domain;
ALTER TABLE portfolios DROP COLUMN IF EXISTS view_count;
ALTER TABLE portfolios DROP COLUMN IF EXISTS last_exported_at;
ALTER TABLE quiz_questions DROP COLUMN IF EXISTS quiz_question_group_id;
ALTER TABLE quiz_questions DROP COLUMN IF EXISTS workflow_state;
ALTER TABLE quiz_submission_answers DROP COLUMN IF EXISTS question_id;
ALTER TABLE quiz_submissions DROP COLUMN IF EXISTS selected_questions;
ALTER TABLE quiz_submissions DROP COLUMN IF EXISTS validation_token;
ALTER TABLE role_overrides DROP COLUMN IF EXISTS account_id;
ALTER TABLE role_overrides DROP COLUMN IF EXISTS role_id;
ALTER TABLE role_overrides DROP COLUMN IF EXISTS context_type;
ALTER TABLE role_overrides DROP COLUMN IF EXISTS context_id;
ALTER TABLE rubric_assessments DROP COLUMN IF EXISTS workflow_state;
ALTER TABLE rubric_associations DROP COLUMN IF EXISTS context_type;
ALTER TABLE rubric_associations DROP COLUMN IF EXISTS context_id;
ALTER TABLE rubrics DROP COLUMN IF EXISTS description;
ALTER TABLE rubrics DROP COLUMN IF EXISTS hide_points;
ALTER TABLE sis_batch_errors DROP COLUMN IF EXISTS row;
ALTER TABLE sis_batch_errors DROP COLUMN IF EXISTS file;
ALTER TABLE sis_batches DROP COLUMN IF EXISTS total_rows;
ALTER TABLE sis_batches DROP COLUMN IF EXISTS processed_rows;
ALTER TABLE student_accommodations DROP COLUMN IF EXISTS description;
ALTER TABLE student_accommodations DROP COLUMN IF EXISTS time_multiplier;
ALTER TABLE student_accommodations DROP COLUMN IF EXISTS extra_days;
ALTER TABLE student_accommodations DROP COLUMN IF EXISTS status;
ALTER TABLE student_accommodations DROP COLUMN IF EXISTS plan_type;
ALTER TABLE student_accommodations DROP COLUMN IF EXISTS plan_external_id;
ALTER TABLE student_accommodations DROP COLUMN IF EXISTS created_by_id;
ALTER TABLE student_accommodations DROP COLUMN IF EXISTS approved_by_id;
ALTER TABLE student_accommodations DROP COLUMN IF EXISTS effective_from;
ALTER TABLE student_accommodations DROP COLUMN IF EXISTS effective_until;
ALTER TABLE submissions DROP COLUMN IF EXISTS posted_at;
ALTER TABLE todays_lesson_overrides DROP COLUMN IF EXISTS link_type;
ALTER TABLE todays_lesson_overrides DROP COLUMN IF EXISTS link_id;
ALTER TABLE todays_lesson_overrides DROP COLUMN IF EXISTS link_url;
ALTER TABLE todays_lesson_overrides DROP COLUMN IF EXISTS label;
ALTER TABLE wiki_pages DROP COLUMN IF EXISTS public;
ALTER TABLE wiki_pages DROP COLUMN IF EXISTS website_mode;

-- === 3. Tables ===
DROP TABLE IF EXISTS quiz_question_groups;
DROP TABLE IF EXISTS question_bank_entries;
DROP TABLE IF EXISTS question_banks;
DROP TABLE IF EXISTS peer_reviews;
DROP TABLE IF EXISTS module_prerequisites;
