// genschema dumps the current database schema as CREATE TABLE + CREATE INDEX
// SQL. Originally used to author 000001_init.up.sql from AutoMigrate output;
// kept around as a debugging aid and as the shared introspection engine for
// cmd/schemadiff.
//
// Usage:
//
//	DATABASE_URL=postgres://... go run ./cmd/genschema > dump.sql
package main

import (
	"fmt"
	"log"
	"sort"

	"github.com/EduThemes/paper-lms/internal/config"
	"github.com/EduThemes/paper-lms/internal/db"
	"github.com/EduThemes/paper-lms/internal/db/schemagen"
	"github.com/joho/godotenv"
)

func sortedTableNames(s *schemagen.Schema) []string {
	out := make([]string, 0, len(s.Tables))
	for k := range s.Tables {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func sortedIndexNames(s *schemagen.Schema) []string {
	out := make([]string, 0, len(s.Indexes))
	for k := range s.Indexes {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func main() {
	_ = godotenv.Load()
	cfg := config.Load()

	database, err := db.Connect(cfg.DatabaseURL)
	if err != nil {
		log.Fatalf("connect: %v", err)
	}
	sqlDB, err := database.DB()
	if err != nil {
		log.Fatalf("sql.DB: %v", err)
	}

	s, err := schemagen.Introspect(sqlDB)
	if err != nil {
		log.Fatalf("introspect: %v", err)
	}

	fmt.Println("-- Paper LMS: schema dump")
	fmt.Println("-- Generated by cmd/genschema")
	fmt.Println()

	// Tables alphabetically — this command is for inspection, not for
	// dependency-correct migration emission. Use cmd/schemadiff for that.
	for _, name := range sortedTableNames(s) {
		fmt.Println(schemagen.RenderCreateTable(s.Tables[name]))
		fmt.Println()
	}
	if len(s.Indexes) > 0 {
		fmt.Println("-- Indexes")
		for _, name := range sortedIndexNames(s) {
			fmt.Println(schemagen.RenderIndex(s.Indexes[name]))
		}
	}
}
